name: Our Products
favicon: null
layout_spectrum: 0.6793035429436713
typography_spectrum: 0.6772417507600039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6588329209480435
  lightness: 0.868412297219038
  saturation: 0.5811512351501733
  rhythmicContrast: 0.3056310312822461
purpose: []
